basePath: /
definitions:
  model.Flag:
    properties:
      amount:
        type: integer
      assetId:
        type: string
      createAt:
        type: string
      days:
        type: integer
      id:
        type: string
      payerId:
        type: string
      task:
        type: string
      timesAchived:
        type: integer
      updateAt:
        type: string
    type: object
info:
  contact: {}
  description: SetFlags API
  license: {}
  title: SetFlags API
  version: 0.0.1
paths:
  /flags:
    get:
      parameters:
      - description: 用户注册接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Flag'
      produces:
      - application/json
      responses:
        "200":
          description: '{"data":{}}'
          schema:
            type: string
      summary: 用户注册账号
      tags:
      - Base
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
